### ISSUE TITLE
Cannot open the controller setup screen.

### ISSUE THREAD

**Issue by DeeHechEss** [wackerl91/script.luna#126] opened 2017-01-22 10:21 UTC
- Luna Version: 0.7.0-rc5
- nVidia GeForce Experience Version:  3.2.2.49
- Moonlight Embedded Version: Not sure, I can find out if its important
- OSMC Version: release 2016.12-1

**Expected Behaviour:**
Opens the controller setup screen
**Actual Behaviour:**
Nothing happens, settings menu and game menu work as normal.

Also the reason im trying to access it is Im trying to get the controller working again, its a generic usb gamepad and it was working yesterday when I first installed all of this and I did make a custom mapping for it with the moonlight command and I was able to set it up in luna properly, this morning nothing works.

**Comment by wackerl91** [comment] 2017-01-22 22:03
Most likely duplicate of #122. 
Wait for the next RC, this should work again afterwards. If it doesn't please reopen this issue and provide the logs.

To resolve your issue in the meantime, you can try to delete the 'input_storage' file in this directory:
`~/.kodi/userdata/addon_data/script.luna/.storage/`. This usually enables you to open the controller config again.

**Closed as completed by wackerl91** 2017-01-22 22:03 UTC
